name: myenv
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pystan
  - fbprophet
  - shap
  - lightgbm==3.3.2
  - pandas==1.1.3
  - numpy
  - scikit-learn
  - category_encoders
  - scipy
  - holidays
  - ephem==4.1.2 