MODEL:
  train_start_date: "2018-01-01"
  train_end_date: "2019-08-31"
  test_start_date: "2019-09-01"
  test_end_date: "2019-09-30"
  prediction_start_date: "2019-10-01"
  prediction_end_date: "2019-10-31"
  target_col_name: "sales"
INPUT:
  sales: "../data/sales.csv"
  taxonomy: "../data/product_taxonomy.csv"
  stores: "../data/store_cities.csv"
OUTPUT:
  path: "../output/predictions.csv"
